import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import swr from 'swr'
import ProductCard from '@/components/ProductCard/ProductCard'
import { Product } from '@prisma/client'

const fetcher = (url: string) => fetch(url).then((res) => res.json())

export default function Home() {
  const { data, error } = swr('/api/getProducts', fetcher)
  let products = data?.products

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {error && <div>Failed to load</div>}
        {!data && <div>Loading...</div>}
        {products && products.map((product: Product) => <ProductCard key={product.id} product={product} />)}
      </main>
    </>
  )
}
